
import java.util.ArrayList;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author Elna
 */
public class Fenetre_Quiz extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Fenetre_Quiz.class.getName());
    ArrayList<Question> questions = new ArrayList<>();
    private int indQC = 0;
    private int SCORE = 0;

    private void afficherQuestionCourante() {
        Question q = questions.get(indQC);
        label_Question.setText(q.getinti());

        Btn_Rep1.setText(q.getp1());
        Btn_Rep2.setText(q.getp2());
        Btn_Rep3.setText(q.getp3());
        Btn_Rep4.setText(q.getp4());

        Btn_Rep1.setEnabled(true);
        Btn_Rep2.setEnabled(true);
        Btn_Rep3.setEnabled(true);
        Btn_Rep4.setEnabled(true);

        label_COOL.setVisible(false);
        label_NUL.setVisible(false);
        Btn_QuestionSuivante.setVisible(false);
    }

    /**
     * Creates new form Fenetre_Quiz
     */
    public Fenetre_Quiz() {
        initComponents();

        questions.add(new Question(
                "Quelle est la capitale de l’Italie ?",
                "Rome", "Milan", "Venise", "Florence", 1));

        questions.add(new Question(
                "Quelle est la capitale du Canada ?",
                "Toronto", "Ottawa", "Montréal", "Vancouver", 2));

        questions.add(new Question(
                "Quelle est la capitale du Japon ?",
                "Kyoto", "Tokyo", "Osaka", "Nagoya", 2));

        questions.add(new Question(
                "Quelle est la capitale de l’Australie ?",
                "Sydney", "Melbourne", "Canberra", "Brisbane", 3));

        questions.add(new Question(
                "Quelle est la capitale du Brésil ?",
                "Rio de Janeiro", "São Paulo", "Brasília", "Salvador", 3));

        afficherQuestionCourante();

    }

    private void verifRep(int numChoisi) {
        // Récupérer la question courante
        Question q = questions.get(indQC);

        // Comparer avec la bonne réponse
        if (numChoisi == q.getindBR()) {
            label_COOL.setVisible(true);
            label_NUL.setVisible(false);

            SCORE++;
            label_SCORE.setText("SCORE : " + SCORE + "/5");
        } else {
            label_COOL.setVisible(false);
            label_NUL.setVisible(true);
        }

        // Désactiver les boutons après réponse
        Btn_Rep1.setEnabled(false);
        Btn_Rep2.setEnabled(false);
        Btn_Rep3.setEnabled(false);
        Btn_Rep4.setEnabled(false);

        // Afficher bouton "suivant"
        Btn_QuestionSuivante.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_Question = new javax.swing.JLabel();
        Btn_Rep1 = new javax.swing.JButton();
        Btn_Rep2 = new javax.swing.JButton();
        Btn_Rep3 = new javax.swing.JButton();
        Btn_Rep4 = new javax.swing.JButton();
        label_COOL = new javax.swing.JLabel();
        Btn_QuestionSuivante = new javax.swing.JButton();
        label_NUL = new javax.swing.JLabel();
        label_SCORE = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label_Question.setText("Question");

        Btn_Rep1.setText("Bouton1");
        Btn_Rep1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Rep1ActionPerformed(evt);
            }
        });

        Btn_Rep2.setText("Bonton2");
        Btn_Rep2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Rep2ActionPerformed(evt);
            }
        });

        Btn_Rep3.setText("Bouton3");
        Btn_Rep3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Rep3ActionPerformed(evt);
            }
        });

        Btn_Rep4.setText("Bouton4");
        Btn_Rep4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Rep4ActionPerformed(evt);
            }
        });

        label_COOL.setText("Bien joué !");

        Btn_QuestionSuivante.setText("Question suivante");
        Btn_QuestionSuivante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_QuestionSuivanteActionPerformed(evt);
            }
        });

        label_NUL.setText("Pas bien joué !");

        label_SCORE.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        label_SCORE.setText("SCORE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(label_COOL))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Btn_QuestionSuivante)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(label_NUL)
                                .addGap(188, 188, 188))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(label_SCORE)
                        .addGap(18, 18, 18))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_Question, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Btn_Rep1)
                            .addComponent(Btn_Rep3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Btn_Rep2)
                            .addComponent(Btn_Rep4))))
                .addGap(71, 71, 71))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(label_SCORE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label_Question)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Rep1)
                    .addComponent(Btn_Rep2))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Rep3)
                    .addComponent(Btn_Rep4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Btn_QuestionSuivante))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(label_NUL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_COOL)
                        .addGap(0, 22, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_Rep4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Rep4ActionPerformed
        verifRep(4);
    }//GEN-LAST:event_Btn_Rep4ActionPerformed

    private void Btn_QuestionSuivanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_QuestionSuivanteActionPerformed
        indQC++;
        if (indQC < 5) {
            afficherQuestionCourante();
        } else {
            label_SCORE.setText("Quiz terminé. SCORE : " + SCORE + " / " + 5);

            Btn_QuestionSuivante.setEnabled(false);
        }
    }//GEN-LAST:event_Btn_QuestionSuivanteActionPerformed

    private void Btn_Rep2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Rep2ActionPerformed
        verifRep(2);
    }//GEN-LAST:event_Btn_Rep2ActionPerformed

    private void Btn_Rep1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Rep1ActionPerformed
        verifRep(1);
    }//GEN-LAST:event_Btn_Rep1ActionPerformed

    private void Btn_Rep3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Rep3ActionPerformed
        verifRep(3);
    }//GEN-LAST:event_Btn_Rep3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Fenetre_Quiz().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_QuestionSuivante;
    private javax.swing.JButton Btn_Rep1;
    private javax.swing.JButton Btn_Rep2;
    private javax.swing.JButton Btn_Rep3;
    private javax.swing.JButton Btn_Rep4;
    private javax.swing.JLabel label_COOL;
    private javax.swing.JLabel label_NUL;
    private javax.swing.JLabel label_Question;
    private javax.swing.JLabel label_SCORE;
    // End of variables declaration//GEN-END:variables
}
