/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Elna
 */
public class Interface extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Interface.class.getName());

    private JeuCadenas jeu;
    
    
    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
        initLogique();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        texte_intro = new javax.swing.JLabel();
        bouton_tester = new javax.swing.JButton();
        texte_score = new javax.swing.JLabel();
        texte_tentatives = new javax.swing.JLabel();
        bouton_recommencer = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        down_chiffre_1 = new javax.swing.JButton();
        down_chiffre_2 = new javax.swing.JButton();
        down_chiffre_3 = new javax.swing.JButton();
        down_chiffre_4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        texte_chiffre_1 = new javax.swing.JLabel();
        texte_chiffre_2 = new javax.swing.JLabel();
        texte_chiffre_3 = new javax.swing.JLabel();
        texte_chiffre_4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        up_chiffre_1 = new javax.swing.JButton();
        up_chiffre_2 = new javax.swing.JButton();
        up_chiffre_3 = new javax.swing.JButton();
        up_chiffre_4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        texte_lbl_nb_chiffres_exacts = new javax.swing.JLabel();
        texte_nb_chiffres_exacts = new javax.swing.JLabel();
        texte_lbl_nb_chiffres_bas = new javax.swing.JLabel();
        texte_nb_chiffres_bas = new javax.swing.JLabel();
        texte_lbl_nb_chiffres_haut = new javax.swing.JLabel();
        texte_nb_chiffres_haut = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        texte_intro.setText("Trouvez le code !");
        getContentPane().add(texte_intro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        bouton_tester.setText("Tester");
        getContentPane().add(bouton_tester, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, -1, -1));

        texte_score.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(texte_score, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));
        getContentPane().add(texte_tentatives, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 130, 10));

        bouton_recommencer.setText("recommencer");
        getContentPane().add(bouton_recommencer, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, -1, -1));

        jPanel1.setLayout(new java.awt.GridLayout(1, 4, 10, 0));

        down_chiffre_1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        down_chiffre_1.setForeground(new java.awt.Color(102, 0, 0));
        down_chiffre_1.setText("\\/");
        jPanel1.add(down_chiffre_1);

        down_chiffre_2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        down_chiffre_2.setForeground(new java.awt.Color(102, 0, 0));
        down_chiffre_2.setText("\\/");
        down_chiffre_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                down_chiffre_2ActionPerformed(evt);
            }
        });
        jPanel1.add(down_chiffre_2);

        down_chiffre_3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        down_chiffre_3.setForeground(new java.awt.Color(102, 0, 0));
        down_chiffre_3.setText("\\/");
        jPanel1.add(down_chiffre_3);

        down_chiffre_4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        down_chiffre_4.setForeground(new java.awt.Color(102, 0, 0));
        down_chiffre_4.setText("\\/");
        down_chiffre_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                down_chiffre_4ActionPerformed(evt);
            }
        });
        jPanel1.add(down_chiffre_4);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 270, 30));

        jPanel3.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        texte_chiffre_1.setFont(new java.awt.Font("Serif", 1, 27)); // NOI18N
        texte_chiffre_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texte_chiffre_1.setText("0");
        texte_chiffre_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0)));
        jPanel3.add(texte_chiffre_1);

        texte_chiffre_2.setFont(new java.awt.Font("Serif", 1, 27)); // NOI18N
        texte_chiffre_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texte_chiffre_2.setText("0");
        texte_chiffre_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0)));
        jPanel3.add(texte_chiffre_2);

        texte_chiffre_3.setFont(new java.awt.Font("Serif", 1, 27)); // NOI18N
        texte_chiffre_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texte_chiffre_3.setText("0");
        texte_chiffre_3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0)));
        jPanel3.add(texte_chiffre_3);

        texte_chiffre_4.setFont(new java.awt.Font("Serif", 1, 27)); // NOI18N
        texte_chiffre_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texte_chiffre_4.setText("0");
        texte_chiffre_4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0)));
        jPanel3.add(texte_chiffre_4);

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 270, 70));

        jPanel4.setLayout(new java.awt.GridLayout(1, 4, 10, 0));

        up_chiffre_1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        up_chiffre_1.setForeground(new java.awt.Color(102, 0, 0));
        up_chiffre_1.setText("/\\");
            up_chiffre_1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    up_chiffre_1ActionPerformed(evt);
                }
            });
            jPanel4.add(up_chiffre_1);

            up_chiffre_2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
            up_chiffre_2.setForeground(new java.awt.Color(102, 0, 0));
            up_chiffre_2.setText("/\\");
                up_chiffre_2.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        up_chiffre_2ActionPerformed(evt);
                    }
                });
                jPanel4.add(up_chiffre_2);

                up_chiffre_3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                up_chiffre_3.setForeground(new java.awt.Color(102, 0, 0));
                up_chiffre_3.setText("/\\");
                    jPanel4.add(up_chiffre_3);

                    up_chiffre_4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
                    up_chiffre_4.setForeground(new java.awt.Color(102, 0, 0));
                    up_chiffre_4.setText("/\\");
                        jPanel4.add(up_chiffre_4);

                        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 270, 30));

                        jPanel2.setLayout(new java.awt.GridLayout(3, 2, 5, 0));

                        texte_lbl_nb_chiffres_exacts.setText("Nombres exacts :");
                        jPanel2.add(texte_lbl_nb_chiffres_exacts);
                        jPanel2.add(texte_nb_chiffres_exacts);

                        texte_lbl_nb_chiffres_bas.setText("Nombres trop bas :");
                        jPanel2.add(texte_lbl_nb_chiffres_bas);
                        jPanel2.add(texte_nb_chiffres_bas);

                        texte_lbl_nb_chiffres_haut.setText("Nombres trop hauts :");
                        jPanel2.add(texte_lbl_nb_chiffres_haut);
                        jPanel2.add(texte_nb_chiffres_haut);

                        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 250, 80));

                        pack();
                    }// </editor-fold>//GEN-END:initComponents

    private void up_chiffre_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_up_chiffre_1ActionPerformed

    private void up_chiffre_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_up_chiffre_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_up_chiffre_2ActionPerformed

    private void down_chiffre_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_down_chiffre_4ActionPerformed

    private void down_chiffre_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_down_chiffre_2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_down_chiffre_2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Interface().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bouton_recommencer;
    private javax.swing.JButton bouton_tester;
    private javax.swing.JButton down_chiffre_1;
    private javax.swing.JButton down_chiffre_2;
    private javax.swing.JButton down_chiffre_3;
    private javax.swing.JButton down_chiffre_4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel texte_chiffre_1;
    private javax.swing.JLabel texte_chiffre_2;
    private javax.swing.JLabel texte_chiffre_3;
    private javax.swing.JLabel texte_chiffre_4;
    private javax.swing.JLabel texte_intro;
    private javax.swing.JLabel texte_lbl_nb_chiffres_bas;
    private javax.swing.JLabel texte_lbl_nb_chiffres_exacts;
    private javax.swing.JLabel texte_lbl_nb_chiffres_haut;
    private javax.swing.JLabel texte_nb_chiffres_bas;
    private javax.swing.JLabel texte_nb_chiffres_exacts;
    private javax.swing.JLabel texte_nb_chiffres_haut;
    private javax.swing.JLabel texte_score;
    private javax.swing.JLabel texte_tentatives;
    private javax.swing.JButton up_chiffre_1;
    private javax.swing.JButton up_chiffre_2;
    private javax.swing.JButton up_chiffre_3;
    private javax.swing.JButton up_chiffre_4;
    // End of variables declaration//GEN-END:variables

    private void initLogique() {

        this.jeu = new JeuCadenas();
        lancerJeuAvecChoix();
        
        bouton_tester.addActionListener(e -> {
            int[] prop = new int[4];
            prop[0] = Integer.parseInt(texte_chiffre_1.getText());
            prop[1] = Integer.parseInt(texte_chiffre_2.getText());
            prop[2] = Integer.parseInt(texte_chiffre_3.getText());
            prop[3] = Integer.parseInt(texte_chiffre_4.getText());
            
            jeu.testerCombinaison(prop);
            
            texte_nb_chiffres_exacts.setText(String.valueOf(jeu.getExacts()));
            texte_nb_chiffres_haut.setText(String.valueOf(jeu.getTropHauts()));
            texte_nb_chiffres_bas.setText(String.valueOf(jeu.getTropBas()));
            texte_tentatives.setText(jeu.getNbTentativesRestantes() + " sur " + jeu.getMaxTentatives());
            
            if (jeu.estGagne()) {
                javax.swing.JOptionPane.showMessageDialog(this, "BRAVO ! Vous avez trouvé !");
                bouton_tester.setEnabled(false);
            } else if (jeu.getNbTentativesRestantes() == 0) {
                String solution = jeu.getSolution();
                javax.swing.JOptionPane.showMessageDialog(this, "PERDU... Le code etait "+ solution);
                bouton_tester.setEnabled(false);
            }
        });

   
        bouton_recommencer.addActionListener(e -> {
            String[] options = {"Facile (20 essais)", "Normal (10 essais)", "Hardcore (5 essais)"};
            int choix = javax.swing.JOptionPane.showOptionDialog(this,
                    "Choisissez la difficulté :",
                    "Nouvelle Partie",
                    javax.swing.JOptionPane.DEFAULT_OPTION,
                    javax.swing.JOptionPane.QUESTION_MESSAGE,
                    null,
                    options,
                    options[1]);

            int nbVies = 10;
            if (choix == 0) nbVies = 20;
            if (choix == 2) nbVies = 5;

            jeu.demarrerNouvellePartie(nbVies);

            texte_chiffre_1.setText("0");
            texte_chiffre_2.setText("0");
            texte_chiffre_3.setText("0");
            texte_chiffre_4.setText("0");
            texte_nb_chiffres_exacts.setText("0");
            texte_nb_chiffres_haut.setText("0");
            texte_nb_chiffres_bas.setText("0");
            
            texte_tentatives.setText(nbVies + " sur " + nbVies);
            
            bouton_tester.setEnabled(true);
        });

        ajouterAction(up_chiffre_1, texte_chiffre_1, 1);
        ajouterAction(up_chiffre_2, texte_chiffre_2, 1);
        ajouterAction(up_chiffre_3, texte_chiffre_3, 1);
        ajouterAction(up_chiffre_4, texte_chiffre_4, 1);
        
        ajouterAction(down_chiffre_1, texte_chiffre_1, -1);
        ajouterAction(down_chiffre_2, texte_chiffre_2, -1);
        ajouterAction(down_chiffre_3, texte_chiffre_3, -1);
        ajouterAction(down_chiffre_4, texte_chiffre_4, -1);
    }

    private void ajouterAction(javax.swing.JButton bouton, javax.swing.JLabel label, int direction) {
        bouton.addActionListener(e -> {
            int val = Integer.parseInt(label.getText());
            val = val + direction;
            if (val > 9) val = 0;
            if (val < 0) val = 9;
            label.setText(String.valueOf(val));
        });
    }
    private void lancerJeuAvecChoix() {
    String[] options = {"Facile (20 essais)", "Normal (10 essais)", "Hardcore (5 essais)"};
            int choix = javax.swing.JOptionPane.showOptionDialog(this,
                    "Choisissez la difficulté :",
                    "Nouvelle Partie",
                    javax.swing.JOptionPane.DEFAULT_OPTION,
                    javax.swing.JOptionPane.QUESTION_MESSAGE,
                    null,
                    options,
                    options[1]);

    int nbVies = 10;
            if (choix == 0) nbVies = 20;
            if (choix == 2) nbVies = 5;

            jeu.demarrerNouvellePartie(nbVies);

            texte_chiffre_1.setText("0");
            texte_chiffre_2.setText("0");
            texte_chiffre_3.setText("0");
            texte_chiffre_4.setText("0");
            texte_nb_chiffres_exacts.setText("0");
            texte_nb_chiffres_haut.setText("0");
            texte_nb_chiffres_bas.setText("0");
            
            texte_tentatives.setText(nbVies + " sur " + nbVies);
            
            bouton_tester.setEnabled(true);
}
}
